First revision of POST support. Rewrote and reorganized _tsws_response function to support it. File upload isn't supported yet and this branch still needs documentation.

diff --git a/tsws b/tsws
--- a/tsws
+++ b/tsws
@@ -198,6 +198,57 @@ function tsws {
   fi
 }
 
+function _tsws_sanitize {
+  # Replace CRLF with \n. Strip backspaces, alert bells, and tabs.
+  # Strip everything but a narrow set of known chars.
+  sed -e $'s/[\r\b\a\t]//g' -e 's/[^-a-zA-Z0-9\/\.\:\;\?\+\*\&\=\,[:space:]]//g'
+}
+
+
+# Via http://unix.stackexchange.com/questions/159253/decoding-url-encoding-percent-encoding
+function _tsws_urldecode {
+  awk -niord '{printf RT?$0chr("0x"substr(RT,2)):$0}' RS=%.. | sed 's/\+/ /g'
+}
+
+function _tsws_parseurl {
+  while read -d $'&' namevaluepair || [ -n "${namevaluepair}" ]; do
+    # Note this method of parsing CGI variables is currently really weak
+    # and ignores & that are escaped as &amp;
+    IFS=$'=' read name value <<< "${namevaluepair}"
+    name="$(_tsws_urldecode <<< "${name}" | _tsws_sanitize)"
+    value="$(_tsws_urldecode <<< "${value}")"
+    _tsws_parsed_url["${name}"]="${value}"
+  done
+}
+
+function tsws_response_headers {
+  local clen="$(cat "$1" | wc -c)"
+  local filetype="$(file -ib "$1")"
+  local content_type="${4:-${filetype}}"
+  printf $'HTTP/1.1 %s %s\r\n' "$2" "$3" | tee "${TSWS_LOG}"
+  printf $'Content-Length: %s\r\n' "${clen}" | tee "${TSWS_LOG}"
+  printf $'Content-Type: %s\r\n' "${content_type}" | tee "${TSWS_LOG}"
+  printf $'Connection: close\r\n' | tee "${TSWS_LOG}"
+  printf $'\r\n' | tee "${TSWS_LOG}"
+}
+
+function tsws_response_body {
+  [ "${method:?}" != "HEAD" ] && cat "$1"
+  rm "$1"
+}
+
+function tsws_500 {
+  printf "Server Error: $2" > "$1"
+  tsws_response_headers "$1" 500 "Internal Server Error" "text/html; charset=utf-8"
+  tsws_response_body "$1"
+}
+
+function tsws_404 {
+  printf "Not found: $2" > "$1"
+  tsws_response_headers "$1" 404 "Not found" "text/html; charset=utf-8"
+  tsws_response_body "$1"
+}
+
 # -----------------------------------------------------------------------------
 # _tsws_response()
 # -----------------------------------------------------------------------------
@@ -206,119 +257,113 @@ function tsws {
 # Do not call it directly.
 #
 function _tsws_response {
-  local method uri path httpvers callback content_type status msg obf clen abs
-  method=""
-  while read -r line; do
-    status=""
-    # Replace CRLF with \n. Strip backspaces, alert bells, and tabs.
-    line="$(sed $'s/[\r\b\a\t]//g' <<< "${line}")"
-    # Sanitize. TODO this santization is probably not complete and may
-    # behave incorrectly for some URLs.
-    line="$(sed 's/[^-a-zA-Z0-9\/\.\:\?\+\*\&\=[:space:]]//g' <<< "${line}")"
-    if [ -n "${line}" ]; then
-      # ${line} is not empty, it is either a "Request-Line" or a header
-      # line. If we have no 'method' yet we assume it is a Request-Line.
-      # http://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html
-      if [ -z "${method}" ]; then
-        read -r method uri httpvers <<< "${line}"
-        continue
-      fi
-      # TODO: if we cared about any of the request headers, here is the
-      # place to read them by parsing ${line}.
-    else
-      # ${line} is empty, so we received two consecutive CRLF.
-      # Process the request.
-      #
-      # Currently all "files" served up by the server are functions in this
-      # script that return content. This shows how dynamic content can be
-      # served and keeps this example all in one single file. It should be
-      # easy to adapt this to also read real files from disk Hint: obf below
-      # and use `file` to get content_type.
-      unset cgi_get
-      local -A cgi_get
-      IFS='?#' read path query fragment <<< "${uri}"
-      while read -d $'&' namevaluepair || [ -n "${namevaluepair}" ]; do
-        # Note this method of parsing CGI variables is currently really weak
-        # and ignores & that are escaped as &amp;
-        IFS=$'=' read name value <<< "${namevaluepair}"
-        # The worst possible unescaping, replace + with space.
-        value="$(sed 's/\+/ /g' <<< "${value}")"
-        cgi_get["${name}"]="${value}"
-      done <<< "${query}"
-      obf="$(mktemp -u)"
-      [ -z "${content_type:-}" ] && content_type="text/plain"
-      case "${method:?}" in
-        GET|HEAD)
-          abs="${TSWS_ROOT:-}/${uri}"
-          if [ -d "${TSWS_ROOT:-}" ] && [ -f "${abs}" ]; then
-            # TSWS_ROOT is defined and the calculated path exists.
-            # First test if the path is inside TSWS_ROOT.
-            local dir="$(dirname "${abs}")"
-            local actualdir="$(cd -- "${dir}" && pwd)"
-            if grep "^${TSWS_ROOT}" <<< "${actualdir}" >/dev/null; then
-              # Yes, the file is inside TSWS_ROOT, serve it up.
-              callback="_tsws_file"
-              content_type="$(file -ib "${abs}")"
-            else
-              # Client is doing something funky with paths, we can't confirm
-              # that the requested file is inside TSWS_ROOT.
-              status=500; msg="Internal Server Error"
-              printf $'Path is outside web root: %s dir=%s actual=%s' "${uri}" "${dir}" "${actualdir}" > "${obf}"
-            fi
-          else
-            # If the file does not exist we go into dynamic callback mode.
-            # Calculate a function name.
-            callback="www$(sed -e 's/\//_/g' -e 's/\./_/g' <<< "${path}")"
-            [ "${callback}" = "www_" ] && callback="www_index"
-            content_type="${callback}_Content_Type"
-            content_type="${!content_type}"
-          fi
-          if local -f  "${callback}" > /dev/null; then
-            # ${callback} is a function we declared.
-            status=200; msg="OK"
-            ${callback} > "${obf}"
-          elif [ -z "${status}" ]; then
-            # ${callback} is not defined and it is not a file, 404.
-            status=404; msg="Not Found"
-            printf $'Not found: %s.' "${path}" > "${obf}"
-          fi
-        ;;
-        *)
-          # Currently we only handle GET and HEAD requests.
-          status=500; msg="Internal Server Error"
-          printf $'Server Error: unknown method %s.' "${method}" > "${obf}"
-        ;;
-      esac
-      clen=$(cat "${obf}"|wc -c)
-      # Log the request.
-      printf $'%s %s' "${method}" "${path} $(date); " >"${TSWS_LOG}"
-      # Output headers, tee shows the response headers in log.
-      printf $'HTTP/1.1 %s %s\r\n' "${status:?}" "${msg:?}" | tee "${TSWS_LOG}"
-      printf $'Content-Length: %s\r\n' "${clen}" | tee "${TSWS_LOG}"
-      printf $'Content-Type: %s\r\n' "${content_type}" | tee "${TSWS_LOG}"
-      printf $'Connection: close\r\n' | tee "${TSWS_LOG}"
-      printf $'\r\n' | tee "${TSWS_LOG}"
-      # Output the response data.
-      [ "${method}" != "HEAD" ] && cat "${obf}"
-      # This is meant to clean up a temporary file so if you alter the code
-      # to handle real files don't let this accidentally delete it!
-      rm "${obf}"
-      # Reset for the next loop iteration.
-      method=""
-    fi
-  done
-}
 
-# -----------------------------------------------------------------------------
-# _tsws_file()
-# -----------------------------------------------------------------------------
-#
-# File server function. If TSWS_ROOT was defined as a valid directory and the
-# request points to an existing file, the abs variable is set and this function
-# is called to supply the content.
-#
-function _tsws_file {
-  cat "${abs:?}"
+  # First line of the request.
+  local method uri httpvers
+  read -r method uri httpvers
+  method="$(_tsws_sanitize <<< "${method}")"
+  uri="$(_tsws_sanitize <<< "${uri}")"
+  httpvers="$(_tsws_sanitize <<< "${httpvers}")"
+  [ -z "${method}" ] && return 0
+
+  # Output buffer file.
+  local obf="$(mktemp -u)"
+
+  # Read the headers into an associative array.
+  local -A request_headers
+  while read -r line; do
+    [ "${line}" = $'\r' ] && break
+    local name="$(sed 's/^\([^:]*\): [^$]*$/\1/g' <<< "${line}")"
+    local value="$(sed 's/^[^:]*: \([^$]*\)$/\1/g' <<< "${line}")"
+    request_headers["${name}"]="${value}"
+  done
+
+  # Process POSTs, load POST data into cgi_post.
+  local -A cgi_post
+  if [ "${method}" = "POST" ]; then
+    local post
+    if [ -z "${request_headers['Content-Length']}" ]; then
+      tsws_500 "${obf}" "No Content-Length on header."
+      return 1
+    fi
+    local clen="${request_headers['Content-Length']}"
+    if [ "${clen}" -neq "${clen}" ] 2>/dev/null; then
+      tsws_500 "${obf}" "Content-Length is not numeric."
+      return 1
+    fi
+    if [ "${clen}" -lt 0 ]; then
+      tsws_500 "${obf}" "Content-Length is not positive."
+      return 1
+    fi
+    if [ "${clen}" -gt 0 ]; then
+      IFS='' read -r -d '' -n "${clen}" post
+      unset _tsws_parsed_url
+      local -A _tsws_parsed_url
+      _tsws_parseurl <<< "${post}"
+      for name in "${!_tsws_parsed_url[@]}"; do
+        cgi_post["${name}"]="${_tsws_parsed_url[${name}]}"
+      done
+    fi
+  fi
+
+  # Process GETs, load URL variables into cgi_get.
+  local -A cgi_get
+  local path query fragment
+  IFS='?#' read path query fragment <<< "${uri}"
+  unset _tsws_parsed_url
+  local -A _tsws_parsed_url
+  _tsws_parseurl <<< "${query}"
+  for name in "${!_tsws_parsed_url[@]}"; do
+    cgi_get["${name}"]="${_tsws_parsed_url[${name}]}"
+  done
+
+  # Check if this is a request for a filesystem file.
+  local abs="${TSWS_ROOT:-}/${uri}"
+  if [ -d "${TSWS_ROOT:-}" ] && [ -f "${abs}" ]; then
+    # TSWS_ROOT is defined and the calculated path exists.
+    # First test if the path is inside TSWS_ROOT.
+    local dir="$(dirname "${abs}")"
+    local actualdir="$(cd -- "${dir}" && pwd)"
+    if grep "^${TSWS_ROOT}" <<< "${actualdir}" >/dev/null; then
+      # The file is inside TSWS_ROOT, serve it up.
+      cp "${abs}" "${obj}"
+      tsws_response_headers "${obf}" 200 "OK"
+      tsws_response_body "${obf}"
+      return 0
+    else
+      # Client is doing something funky with paths, we can't confirm
+      # that the requested file is inside TSWS_ROOT.
+      tsws_500 "${obf}" "Path is outside web root: ${uri} dir=${dir} actual=${actualdir}."
+      return 1
+    fi
+  fi
+
+  # Set host and port.
+  local host port
+  unset host port
+  IFS=':' read -r host port <<< "${request_headers['Host']}"
+
+  # Callback and Content-Type.
+  local callback="www$(sed -e 's/\//_/g' -e 's/\./_/g' <<< "${path}")"
+  [ "${callback}" = "www_" ] && callback="www_index"
+  local content_type="${callback}_Content_Type"
+  content_type="${!content_type}"
+  if ! local -f "${callback}" > /dev/null; then
+    tsws_404 "$1" "${url}"
+    return 1
+  fi
+
+  # Dispatch.
+  case "${method:?}" in
+    GET|HEAD|POST)
+      ${callback} > "${obf}"
+      tsws_response_headers "${obf}" 200 "OK" "${content_type}"
+      tsws_response_body "${obf}"
+    ;;
+    *)
+      tsws_500 "${obf}" "unimplemented method ${method}."
+    ;;
+  esac
 }
 
 # +---------------------------------------------------------------------------+
@@ -362,7 +407,7 @@ cat <<EOF
         <td>$(uname -r)</td>
       </tr>
       <tr>
-        <td class="th">Host</td>
+        <td class="th">Server host</td>
         <td>$(uname -n)</td>
       </tr>
       <tr>
@@ -378,22 +423,18 @@ cat <<EOF
         <td>$(uname -i)</td>
       </tr>
       <tr>
-        <td class="th">Operating System</td>
+        <td class="th">Operating system</td>
         <td>$(uname -o)</td>
       </tr>
       $( [ -x "$(which lsb_release 2>/dev/null)" ] &&
         echo "<tr><td class="th">Distribution</td><td>$(lsb_release -ds)</td></tr>")
       <tr>
-        <td class="th">HTTP Version</td>
+        <td class="th">HTTP version</td>
         <td>${httpvers}</td>
       </tr>
       <tr>
-        <td class="th">TSWS Version</td>
+        <td class="th">TSWS version</td>
         <td>${TSWS_VERSION}</td>
-      </tr>
-      <tr>
-        <td class="th">Status</td>
-        <td>${status} ${msg}</td>
       </tr>
       <tr>
         <td class="th">Method</td>
@@ -407,16 +448,51 @@ cat <<EOF
         <td class="th">Callback</td>
         <td>${callback}</td>
       </tr>
+      <tr>
+        <td class="th">Content-Type</td>
+        <td>${content_type}</td>
+      </tr>
+      <tr>
+        <td class="th">Client host</td>
+        <td>${host}</td>
+      </tr>
+      <tr>
+        <td class="th">Client port</td>
+        <td>${port}</td>
+      </tr>
     </table>
-    $(if [ ${#cgi_get[@]} -gt 0 ]; then
-      echo $'<h3>CGI GET vars:</H3>\n<table>'
-      for name in "${!cgi_get[@]}"; do
-        echo "<tr><td class="th">${name}</td><td>${cgi_get["${name}"]}</td></tr>"
-      done
-      echo "</table>"
-    else
-      echo "<p><a href='/?a=123&b=test+123&c=xyz#fragmentjumpythingy'>Test CGI GET vars</a></p>"
-    fi)
+    <fieldset>
+      <legend>Request Headers</legend>
+      <table>
+        $(for name in "${!request_headers[@]}"; do
+          echo "<tr><td class="th">${name}</td><td>${request_headers["${name}"]}</td></tr>"
+        done)
+      </table>
+    </fieldset>
+    <fieldset class='get'>
+      <legend>Test CGI GET</legend>
+      $(if [ -n "${cgi_get[*]:-}" ] && [ ${#cgi_get[@]} -gt 0 ]; then
+        echo $'<table>'
+        for name in "${!cgi_get[@]}"; do
+          echo "<tr><td class="th">${name}</td><td>${cgi_get["${name}"]}</td></tr>"
+        done
+        echo "</table><aside class="controls-right"><a href='/'>reset</a></aside>"
+      else
+        echo "<a href='/?a=123&b=test+123&c=xyz#fragmentjumpythingy'>Test CGI GET vars</a>"
+      fi)
+    </fieldset>
+    <fieldset class='post'>
+      <legend>Test CGI POST</legend>
+      $(if [ -n "${cgi_post[*]:-}" ] && [ ${#cgi_post[@]} -gt 0 ]; then
+        echo $'<table>'
+        for name in "${!cgi_post[@]}"; do
+          echo "<tr><td class="th">${name}</td><td><pre>${cgi_post["${name}"]}</pre></td></tr>"
+        done
+        echo "</table><aside class="controls-right"><a href='/'>reset</a></aside>"
+      else
+        echo "<form method='POST'><textarea name='texty'></textarea><br><input class='submit' type='submit' name='submit' value='Test POST'></form>"
+      fi)
+    </fieldset>
     <a href="https://github.com/dfletcher/tsws" title="Fork me on GitHub"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/e7bbb0521b397edbd5fe43e7f760759336b5e05f/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677265656e5f3030373230302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_green_007200.png"></a>
   </body>
 </html>
@@ -453,6 +529,85 @@ TABLE {
 TD {
   vertical-align: top;
   white-space: nowrap;
+}
+
+PRE {
+  margin: 0.185em 0 0 0;
+}
+
+FORM {
+  text-align: right;
+}
+
+FIELDSET {
+  margin: 2em 0;
+  padding: 1em;
+}
+
+LEGEND {
+  padding: 0 .5em;
+  font-weight: bold;
+}
+
+TEXTAREA {
+  width: 90%;
+  display: block;
+  margin: 1em;
+  height: 6em;
+  padding: 1em;
+}
+
+INPUT.submit {
+  margin: 0 1em 1em 0;
+  -moz-box-shadow:inset 0px 1px 0px 0px #ffffff;
+  -webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;
+  box-shadow:inset 0px 1px 0px 0px #ffffff;
+  background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #ffffff), color-stop(1, #f6f6f6));
+  background:-moz-linear-gradient(top, #ffffff 5%, #f6f6f6 100%);
+  background:-webkit-linear-gradient(top, #ffffff 5%, #f6f6f6 100%);
+  background:-o-linear-gradient(top, #ffffff 5%, #f6f6f6 100%);
+  background:-ms-linear-gradient(top, #ffffff 5%, #f6f6f6 100%);
+  background:linear-gradient(to bottom, #ffffff 5%, #f6f6f6 100%);
+  filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffff', endColorstr='#f6f6f6',GradientType=0);
+  background-color:#ffffff;
+  -moz-border-radius:6px;
+  -webkit-border-radius:6px;
+  border-radius:6px;
+  border:1px solid #dcdcdc;
+  display:inline-block;
+  cursor:pointer;
+  color:#666666;
+  font-family:Arial;
+  font-size:13px;
+  font-weight:bold;
+  padding:6px 24px;
+  text-decoration:none;
+  text-shadow:0px 1px 0px #ffffff;
+}
+
+INPUT.submit:hover {
+  background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #f6f6f6), color-stop(1, #ffffff));
+  background:-moz-linear-gradient(top, #f6f6f6 5%, #ffffff 100%);
+  background:-webkit-linear-gradient(top, #f6f6f6 5%, #ffffff 100%);
+  background:-o-linear-gradient(top, #f6f6f6 5%, #ffffff 100%);
+  background:-ms-linear-gradient(top, #f6f6f6 5%, #ffffff 100%);
+  background:linear-gradient(to bottom, #f6f6f6 5%, #ffffff 100%);
+  filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#f6f6f6', endColorstr='#ffffff',GradientType=0);
+  background-color:#f6f6f6;
+}
+
+INPUT.submit:active {
+  position:relative;
+  top:1px;
+}
+
+FIELDSET.post td {
+  padding-bottom: 1em;
+}
+
+.controls-right {
+  text-align: right;
+  margin-right: 1em;
 }
 
 .th {
